//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#define CBOX_WIDTH	800
#define CBOX_HEIGHT	600

#define IDI_ICON         101
#define ID_PROCESSOR_VENDOR_COMBOBOX	2001
#define ID_PROCESSOR_SUBTYPE_COMBOBOX	2002
#define ID_PROCESSOR_MODEL_COMBOBOX		2003

#define ID_CBOX_MOTHERBOARD_VENDOR	2004
#define ID_CBOX_MOTHERBOARD_MODEL	2005

#define ID_CBOX_RAM_VENDOR		2006
#define ID_CBOX_RAM_TYPE		3007
#define ID_CBOX_RAM_CAPACITY	3008

#define ID_CBOX_GPU_VENDOR	2009
#define ID_CBOX_GPU_SERIES	2010
#define ID_CBOX_GPU_MODEL	2011

#define ID_CBOX_STORAGE_VENDOR		2012
#define ID_CBOX_STORAGE_CAPACITY	2013
#define ID_CBOX_STORAGE_SPEED		2014

#define ID_CBOX_MONITOR_VENDOR			2015
#define ID_CBOX_MONITOR_SCREENSIZE		2016
#define ID_CBOX_MONITOR_RESOLUTION		2017

#define ID_CBOX_OPTICAL_DRIVE_VENDOR	2018
#define ID_CBOX_OPTICAL_DRIVE_SPEED		2019

#define ID_CBOX_POWERSUPPLY_VENDOR		1020
#define ID_CBOX_POWERSUPPLY_CAPACITY	1021

#define ID_CBOX_CABINET_VENDOR			2022
#define ID_CBOX_CABINET_FORMFACTOR		2023

#define ID_CBOX_KEYBOARD_VENDOR			2024
#define ID_CBOX_KEYBOARD_INTERFACE		2025

#define ID_CBOX_MOUSE_VENDOR			2026
#define ID_CBOX_MOUSE_TYPE				2027	// wired/wireless

#define ID_EDITBOX_NAME		2030

#define IDC_COMBOBOX_TEXT	401

#define IDB_BITMAP	501



